### ISSUE TITLE
CoreData Warnings

### ISSUE THREAD

**Issue by jkmassel** [Automattic/Automattic-Tracks-iOS#108]
The following warnings are showing up in Xcode 11:

>2019-09-03 08:11:00.143612-0600 WordPress[16903:1586628] [error] CoreData: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.

>CoreData: warning: Property 'customProperties' on Entity 'TracksEvent' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

>CoreData: warning: Property 'deviceInfo' on Entity 'TracksEvent' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

>CoreData: warning: Property 'userProperties' on Entity 'TracksEvent' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

**Comment by dsngeu** [comment]
I got the same issue with Xcode 11 and iOS 13

**Comment by jkmassel** [comment]
Fixed by @etoledom in https://github.com/Automattic/Automattic-Tracks-iOS/pull/118!

🎉
