### ISSUE TITLE
Where to store SQLite DB in non-sandboxed apps?

### ISSUE THREAD

**Issue by mokagio** [Automattic/Automattic-Tracks-iOS#146]
I'm working on adding support to an internal macOS app that is not sandboxed.

At launch I get prompted for access to the user's `~/Documents` folder.

I tracked it down to [`TracksContextManager` storing `.sqlite` DB at the URL for an `applicationDocumentsDirectory`](https://github.com/Automattic/Automattic-Tracks-iOS/blob/5f96537a62a8b7d3eb6635cb4dd8489dd39fc62a/Automattic-Tracks-iOS/Model/Core%20Data/TracksContextManager.m#L45-L57) computed as:

```objc
[[[NSFileManager defaultManager] URLsForDirectory:NSDocumentDirectory 
                                 inDomains:NSUserDomainMask] lastObject];
```

When running in a sandboxed app, like Simplenote for macOS, this path is 

```
~/Library/Containers/com.automattic.SimplenoteMac/Data/Documents
```

but for a non-sandboxed app, the path is `~/Documents`.

I think a good replacement would be the Application Support folder. Here's what the [macOS Library Directory Details](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/MacOSXDirectories/MacOSXDirectories.html#//apple_ref/doc/uid/TP40010672-CH10-SW1) documentation says about it:

> Contains all app-specific data and support files. These are the files that your app creates and manages on behalf of the user and can include files that contain user data.

@jkmassel @jleandroperez what do you think?

**Comment by mokagio** [comment]
I opened #147 to use Application Support instead of Documents and pointed the internal non-sandboxed app to it. It works fine now.

CI was failing since I integrated tracks due to a timeout because the app prompted for Documents access. The tests are now passing.

**Comment by jleandroperez** [comment]
Yup @mokagio !! ApplicationSupport works super in these scenarios. Simperium uses that folder to keep track of "unsent changes".

[Ref. here!](https://github.com/Simperium/simperium-ios/blob/develop/Simperium/SPPersistentMutableDictionary.m#L399)

**Comment by mokagio** [comment]
Excellent!

I'm not familiar with the way Tracks works. Do you know if there would be consequences in the Simplenote macOS behavior if we merged #147?

I imagine it may end up loosing all those events that haven't been log between the time the app restarted for the update and the new store being installed in Application Support.

I assume the impact would be negligible, but I'm not sure how to assess it.

An alternative could be to default to sandboxed Documents and then add an option init Tracks pointing to Application Support that non-sandboxed apps can use.

cc @jkmassel.

**Comment by jleandroperez** [comment]
@mokagio Exactly! (AFAIK) worst case scenario, events that were not uploaded would get lost. 

We should test, though, what happens with [this API](https://github.com/Automattic/Automattic-Tracks-iOS/pull/147/files#diff-0e5f9294e3ef8eb1d50ea733ed22b9f5R67). 

That is: verify exactly where that URL ends up pointing to, in sandboxed / non sandboxed environments.

**Comment by mokagio** [comment]
I checked and the Application Support for a sandboxed app like Simplenote still points to the sandbox

```
~/Library/Containers/com.automattic.SimplenoteMac.beta/Data/Library/Application%20Support/com.automattic.SimplenoteMac.beta/Tracks.sqlite
```

![image](https://user-images.githubusercontent.com/1218433/94755213-162f9080-03d7-11eb-8520-ce41c4447121.png)

**Comment by mokagio** [comment]
Anyways, I had a chat with @jkmassel and we agreed to got for a flag to allow Tracks consumers to configure where to store the DB (Documents vs Application Support) for now. 

This will allow us to keep Simplenote macOS behaving as it currently does and think whether to change the approach without the time constrain of the other app update needing to land.

**Comment by jleandroperez** [comment]
Sounds good sir!

**Comment by mokagio** [comment]
I'm going to close this on the basis that the question "Where to store the SQLite BD in non-sandboxed apps?" has been answered: `~/Application Support`.

The rest of the suggestions in this issue are for the future and not necessarily something we'll need to tackle soon.
