### ISSUE TITLE
Switch back to official Sodium pod

### ISSUE THREAD

**Issue by mokagio** [Automattic/Automattic-Tracks-iOS#154]
Now that CocoaPods 1.10.0 has been released, if we upgrade the tooling here, we should be able to switch back to the official Sodium pod.

See:

- https://github.com/jedisct1/swift-sodium/pull/214
- #148

**Comment by jkmassel** [comment]
This was done in https://github.com/Automattic/Automattic-Tracks-iOS/pull/160 🎉
