### ISSUE TITLE
Validation errors on event names

### ISSUE THREAD

**Issue by koke** [Automattic/Automattic-Tracks-iOS#19]
I'm seeing a bunch of these:

> 2015-06-16 13:05:22:331 WordPress[8098:807] Error when validating TracksEvent: Error Domain=TracksErrorDomain Code=3 "An event name contain alpha characters and underscores only." UserInfo=0x17447d000 {NSLocalizedDescription=An event name contain alpha characters and underscores only.}

When I went to debug:

```
(lldb) po error
Error Domain=TracksErrorDomain Code=3 "An event name contain alpha characters and underscores only." UserInfo=0x17447d000 {NSLocalizedDescription=An event name contain alpha characters and underscores only.}

(lldb) po tracksEvent.eventName
wpios_logout
```

**Comment by astralbodies** [comment]
In this specific case wpios_logout was an invalid name (needs prefix_subject_verb). Resolved with https://github.com/wordpress-mobile/WordPress-iOS/pull/3960 .
