### ISSUE TITLE
Remove deprecated `statusBarFrame` usages

### ISSUE THREAD

**Issue by mokagio** [Automattic/Automattic-Tracks-iOS#273]
The 3.1.0 CI deployment failed because of deprecation warnings:

```
- WARN  \| xcodebuild:  /opt/ci/builds/builder/automattic/tracks-ios/Sources/Model/ObjC/Common/TracksDeviceInformation.m:177:48:
  warning: 'statusBarFrame' is deprecated: first deprecated in iOS 13.0
    - Use the statusBarManager property of the window scene instead. [-Wdeprecated-declarations]
```

We could work around this by passing `--allow-warnings` to the pod validation command via our CI plugin, but I think it's best we remain strict in our validation and address this deprecation. It's deprecated for a reason, after all.

It should be straightforward to update the code to use the new recommended syntax ([see StackOverflow, for example](https://stackoverflow.com/questions/57023899/how-to-get-the-status-bar-height-in-ios-13)).

**Comment by crazytonyli** [comment]
This `statusBarFrame` is used to [track status bar height](https://github.com/Automattic/Automattic-Tracks-iOS/blob/3.2.0/Sources/Event%20Logging/TracksService.m#L413). But is that information really useful to us? If it's not, can we just delete it?

There is also another similar deprecated API usage: [`statusBarOrientation`](https://github.com/Automattic/Automattic-Tracks-iOS/blob/b6979ef69b4b094c8809ba83661222dcd0d7667e/Sources/Model/ObjC/Common/TracksDeviceInformation.m#L196). It's used to track device orientation. I think this information can be useful. But I think it's more appropriate to use [`UIDevice.orientation`](https://developer.apple.com/documentation/uikit/uidevice/1620053-orientation) instead.

**Comment by bjhomer** [comment]
Another problem: both of these APIs can only accessed on the main thread. This means that every Tracks call from a non-main thread is making a _blocking_ call to the main thread to fetch the status bar frame.

If nobody's using this information, I'd agree with removing it.
